# Yup
# [ table-key ]
# [ table-key.dotted ]
# my-false_identifier = false
# "my true identifer" = true
# intval = 123
# "quoted identifier" = 11_000_000.45
# qstr = "Quoted string"
# lstr = 'Literal string'
# hex = 0xFF
# bin = 0b1011
# oct = 0o0111
# exp = 1e-2
# swestr = "Lök på laxen å dä"
# emoji = "😂"
# float = 0.12
# hex = 0xFF
# oct = 0o0734
# bin = 0b011100
# exp = 0E2
# local-time = 00:00:00.001
# full-date = 2020-12-01
# local-date-time = 2020-12-12T00:00:00
# offset-date-time = 2020-12-12T00:00:00.001+10:00
# inf = inf
# nan = nan
# negint = -12
# neginf = -inf
# negnan = -nan

# key1=1
# key2= 1

# simple-array = [ 1 , 2 ]
# simple-value = 1
# simple-table = { str = "value", num = 2, nested-array = [ { v = [1,2], c = 2 }, { v = [1,2] } ] }

# simple-table = {version = "2.0.0", nested-table = { sub = 1},  optional = true }

# mulquotstr = """
#   This is some
#   multiline string with a " single quote in it"""

# # mullitstr = '''
# #   A multiline with literal's
# #   '''

# ---------------------

# root-str = "I am Root"
# root-flt = 1.2e-3

# [key.sub]
# float = 1.23
# str = 'ney'
# # hex = 0xFF

# [key]
# int = 12
# str = "yay"
# # time = 12:12:12
# date = 2020-12-12T12:12:12+12:00

# [ key . sub. sam ]
# str = 'way'

# [key.bim]
# bin = [0b1101, 0b111]
# fa = "way"
# 1="yes"
# 2="no"

# [table.deep]
# key = 1

# [table.root]
# key = { val = 'a', bajs = 'yes' }

# [table]
# key = 3

# [top]
# always = "yes"

# [[top.array]]
# key = 1
# key2 = { key = "one", val = 1 }

# [[top.array]]
# key = 1
# key2 = { key = "two", val = 2 }

# str = "Name\tJos\u00E9\nLoc\t\"SF\"\f."

# str = """\
# The quick brown \


#   fox jumps over \
#     the lazy dog."""

# str4 = """\
#        The quick brown \
#        fox jumps over \
#        the lazy \t dog.\
#        """

regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
